# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 12:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=200)),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2016, 3, 8, 12, 32, 56, 841996), verbose_name='date published')),
                ('last_modified_date', models.DateTimeField(verbose_name='date modified')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2016, 3, 8, 12, 32, 56, 880895), verbose_name='date published')),
                ('last_modified_date', models.DateTimeField(verbose_name='date modified')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Item')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
