# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 14:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='item',
        ),
        migrations.AlterField(
            model_name='question',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 9, 14, 40, 33, 293411), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
