# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 17:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='last_modified_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 7, 17, 19, 49, 368454), verbose_name='date modified'),
        ),
    ]
