# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 11:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_question_last_modified_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime(2016, 3, 8, 11, 43, 56, 65478), verbose_name='date modified')),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SubQuestion'),
        ),
        migrations.AlterField(
            model_name='question',
            name='last_modified_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 8, 11, 43, 56, 49675), verbose_name='date modified'),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='sub_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Question'),
        ),
    ]
