# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 12:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160308_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subquestion',
            old_name='sub_question',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='question',
            name='last_modified_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 8, 11, 59, 46, 817830), verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='last_modified_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 8, 11, 59, 46, 833291), verbose_name='date modified'),
        ),
    ]
