# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 11:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_create_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 16, 11, 23, 56, 645837), verbose_name='date created'),
        ),
    ]
